### ISSUE TITLE
Method 文件夹不存在

### ISSUE THREAD

**Issue by WJinhai** [lxh21k/Super-Resolution#1]
您好，最近在研究传统的超分辨率重建方法，看到了你发布的代码，但是代码中并没有Method文件夹，是否遗漏了？

**Comment by lxh21k** [comment]
你好，Method部分还没有写完。若有需要可以参考 R. Timofte, V. De Smet, and L. Van Gool. Anchored Neighborhood Regression for Fast Example-Based Super-Resolution. In International Conference on Computer Vision (ICCV 2013), December 2013, Australia. 这篇文章的源代码。代码下载链接为：https://people.ee.ethz.ch/~timofter/software/SR_NE_ANR.zip
